CREATE OR REPLACE FUNCTION OBTENER_TOTAL_CARRITO(
    ID_CARRITO_C INT
)
RETURNS INT
BEGIN 
	DECLARE SALIDA INT;
	SELECT SUM(SUB_TOTAL) INTO SALIDA FROM VER_DETALLE vd WHERE vd.ID_CARRITO = ID_CARRITO_C;
RETURN SALIDA;
END;

CREATE OR REPLACE FUNCTION OBTENER_TIEMPO_CARRITO(
    ID_CARRITO_C INT
)
RETURNS INT
BEGIN 
	DECLARE SALIDA INT;
	SELECT SUM(T_PREPARACION) INTO SALIDA FROM VER_DETALLE vd WHERE vd.ID_CARRITO = ID_CARRITO_C;
RETURN SALIDA;
END;