CREATE OR REPLACE TRIGGER TRIGGER_CARRITO_INSERT AFTER INSERT ON DETALLE FOR EACH ROW
BEGIN
	DECLARE NUEVO_TOTAL INT;
	DECLARE TIEMPO_TOTAL INT;
	DECLARE ID INT; 
	SET ID = NEW.ID_CARRITO;
	SET NUEVO_TOTAL = OBTENER_TOTAL_CARRITO(ID);
	SET TIEMPO_TOTAL = OBTENER_TIEMPO_CARRITO(ID);
	UPDATE CARRITO 
		SET TOTAL = NUEVO_TOTAL, TIEMPO_ESTIMADO = TIEMPO_TOTAL WHERE ID_CARRITO = ID;
END;

CREATE OR REPLACE TRIGGER TRIGGER_CARRITO_DELETE AFTER DELETE ON DETALLE FOR EACH ROW
BEGIN
	DECLARE NUEVO_TOTAL INT;
	DECLARE TIEMPO_TOTAL INT;
	DECLARE ID INT; 
	SET ID = OLD.ID_CARRITO;
	SET NUEVO_TOTAL = OBTENER_TOTAL_CARRITO(ID);
	SET TIEMPO_TOTAL = OBTENER_TIEMPO_CARRITO(ID);
	UPDATE CARRITO 
		SET TOTAL = NUEVO_TOTAL, TIEMPO_ESTIMADO = TIEMPO_TOTAL WHERE ID_CARRITO = ID;
END;