CREATE OR REPLACE VIEW VER_CATEGORIAS AS 
SELECT ID_CATEGORIA, NOMBRE, DESCRIPCION FROM CATEGORIA;



CREATE OR REPLACE VIEW VER_PRODUCTOS AS 
SELECT PRODUCTO.ID_PRODUCTO, PRODUCTO.NOMBRE, PRODUCTO.PRECIO, PRODUCTO.T_PREPARACION, CATEGORIA.NOMBRE AS NOMBRE_CATEGORIA FROM PRODUCTO
INNER JOIN CATEGORIA 
ON PRODUCTO.ID_CATEGORIA = CATEGORIA.ID_CATEGORIA;



CREATE OR REPLACE VIEW VER_DETALLE AS 
SELECT ID_CARRITO, NOMBRE, PRECIO, CANTIDAD, T_PREPARACION ,PRECIO * CANTIDAD AS SUB_TOTAL
FROM DETALLE
INNER JOIN PRODUCTO p 
ON DETALLE.ID_PRODUCTO = p.ID_PRODUCTO;


CREATE OR REPLACE VIEW VER_REPARTIDORES
AS SELECT ID_REPARTIDOR AS ID, NOMBRE , VEHICULO , TELEFONO FROM REPARTIDOR;


